import './globals.css'
import type { Metadata } from 'next'
// import { Inter } from 'next/font/google'
import { Nanum_Myeongjo } from 'next/font/google'

const inter = Nanum_Myeongjo({
  weight: ['400', '700', '800'],
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: '성간여행일기',
  description: 'Generated by create next app',
}

export default function RootLayout({
                                     children,
                                   }: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
    <head>
      {/*<link rel="preconnect" href="https://fonts.googleapis.com"/>*/}
      {/*<link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin={"anonymous"}/>*/}
      {/*<link href="https://fonts.googleapis.com/css2?family=Nanum+Myeongjo:wght@400;700;800&display=swap"*/}
      {/*      rel="stylesheet"/>*/}
    </head>
    <body className={inter.className}>{children}</body>
    </html>
  )
}
